import { COLOR_FAMILIES } from "@/lib/colorFamilies";
import { VIBE_TAGS } from "@/lib/vibeTagging";

// Validation for the URL query params that feed gallery/buddy database
// filters, in the same spirit as resolvePageSize (src/lib/pageSize.ts) and
// resolveSort (src/queries/gallery.ts): a raw query-string value is
// attacker-controllable, so it's constrained to a known-good shape rather
// than passed through to Prisma on trust.
//
// This exists because it wasn't, and that was a real bug: `?color=%00bad`
// (and the same for weaponId/tierId/themeId/vibe) reached Postgres, which
// rejects NUL bytes outright with `invalid byte sequence for encoding
// "UTF8": 0x00`, turning a junk URL into a 500. Not a data-leak - Prisma
// parameterises, so nothing was injectable - but any bot probing query
// strings could fill production logs with server errors, and a mangled
// shared link would show a crash page instead of simply "no matches".
//
// Everything here fails soft: an unrecognised value becomes `undefined`,
// which the query layer treats as "filter not applied". That's deliberate.
// A malformed filter should degrade to an unfiltered view, not an error - it
// is far more likely to be a truncated link someone pasted than an attack.

/**
 * valorant-api.com ids are UUIDs. Also accepts our own synthetic collection
 * group ids ("group:vct", "group:name:Reaver" - see collectionGroups.ts),
 * which are generated by this app rather than upstream and are matched
 * exactly by the query layer.
 */
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const COLLECTION_GROUP = /^group:[a-z]+(:.{1,200})?$/i;

export function resolveCatalogId(raw: string | undefined): string | undefined {
  return raw && UUID.test(raw) ? raw : undefined;
}

/** Theme ids may additionally be a synthetic collection-group id. */
export function resolveThemeId(raw: string | undefined): string | undefined {
  if (!raw) return undefined;
  if (UUID.test(raw)) return raw;
  // Decoding is what the query layer does too; a group id carrying an
  // unencodable name is not one we produced.
  if (COLLECTION_GROUP.test(raw)) {
    try {
      decodeURIComponent(raw);
      return raw;
    } catch {
      return undefined;
    }
  }
  return undefined;
}

export function resolveColor(raw: string | undefined): string | undefined {
  return raw && COLOR_FAMILIES.includes(raw) ? raw : undefined;
}

export function resolveVibe(raw: string | undefined): string | undefined {
  return raw && (VIBE_TAGS as readonly string[]).includes(raw) ? raw : undefined;
}

/**
 * Free-text search is the one filter with no allowlist to check against, so
 * it's sanitised instead: control characters (NUL included) stripped, and
 * length capped. The cap matters because the fuzzy-search path scores the
 * query against every candidate skin name in JS - an unbounded string turns
 * that into pointless work on every keystroke.
 */
export function resolveSearch(raw: string | undefined): string | undefined {
  if (!raw) return undefined;
  const cleaned = raw.replace(/[\u0000-\u001f\u007f]/g, "").trim().slice(0, 100);
  return cleaned.length > 0 ? cleaned : undefined;
}
