import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  resolveCatalogId,
  resolveThemeId,
  resolveColor,
  resolveVibe,
  resolveSearch,
} from "@/lib/filterParams";

const REAL_UUID = "18609205-4edb-5966-cff8-0fba0230ba1e";

// The regression these guard: an unvalidated query param reached a Prisma
// `where` clause, and a NUL byte in it made Postgres reject the query
// outright (`invalid byte sequence for encoding "UTF8": 0x00`) - turning a
// junk URL into a 500 instead of an empty result set. Verified against the
// live app before the fix: /?color=%00bad and four sibling params all 500'd.

describe("resolveCatalogId", () => {
  it("accepts a real catalog uuid", () => {
    assert.equal(resolveCatalogId(REAL_UUID), REAL_UUID);
  });

  it("rejects a NUL byte - the exact input that caused a 500", () => {
    assert.equal(resolveCatalogId("\u0000bad"), undefined);
  });

  it("rejects anything that isn't uuid-shaped", () => {
    for (const bad of ["", "bad", "'; DROP TABLE skins;--", REAL_UUID + "x", "../../etc/passwd"]) {
      assert.equal(resolveCatalogId(bad), undefined, bad);
    }
  });

  it("rejects undefined", () => {
    assert.equal(resolveCatalogId(undefined), undefined);
  });
});

describe("resolveThemeId", () => {
  it("accepts a real uuid", () => {
    assert.equal(resolveThemeId(REAL_UUID), REAL_UUID);
  });

  it("accepts our synthetic collection-group ids", () => {
    // These are generated by this app (src/lib/collectionGroups.ts), not
    // upstream, so they're legitimately not uuid-shaped.
    assert.equal(resolveThemeId("group:vct"), "group:vct");
    assert.equal(resolveThemeId("group:name:Reaver"), "group:name:Reaver");
  });

  it("rejects a NUL byte and other junk", () => {
    for (const bad of ["\u0000bad", "group:", "notagroup:x", "bad"]) {
      assert.equal(resolveThemeId(bad), undefined, JSON.stringify(bad));
    }
  });
});

describe("resolveColor / resolveVibe", () => {
  it("accepts values from the real vocabularies", () => {
    assert.equal(resolveColor("red"), "red");
    assert.equal(resolveVibe("dark"), "dark");
  });

  it("rejects anything outside the allowlist, including a NUL byte", () => {
    for (const bad of ["\u0000bad", "chartreuse", "", "RED"]) {
      assert.equal(resolveColor(bad), undefined, JSON.stringify(bad));
      assert.equal(resolveVibe(bad), undefined, JSON.stringify(bad));
    }
  });
});

describe("resolveSearch", () => {
  it("passes ordinary search text through, trimmed", () => {
    assert.equal(resolveSearch("  elderflame  "), "elderflame");
  });

  it("strips control characters rather than rejecting the whole query", () => {
    // Free text has no allowlist to check against, so it's sanitised - and a
    // user shouldn't lose their whole search because one bad byte crept in.
    assert.equal(resolveSearch("elder\u0000flame"), "elderflame");
  });

  it("returns undefined when nothing survives sanitising", () => {
    assert.equal(resolveSearch("\u0000\u0001"), undefined);
    assert.equal(resolveSearch("   "), undefined);
    assert.equal(resolveSearch(undefined), undefined);
  });

  it("caps length, since the fuzzy path scores the query against every skin", () => {
    assert.equal(resolveSearch("a".repeat(500))?.length, 100);
  });
});
